name: Deploy - Web App

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy-web:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build web app
      run: flutter build web --release --web-renderer html
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/web
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  deploy-android:
    name: Deploy Android APK
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Android APK
      run: flutter build apk --release
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/*.apk
        tag_name: v${{ github.run_number }}
        name: MedCalc v${{ github.run_number }}
        body: |
          ## MedCalc - Medical Calculator App
          
          ### What's New
          - Latest updates and improvements
          - Bug fixes and performance enhancements
          
          ### Download
          - **Android APK**: Download the APK file below
          - **Web App**: Available at [GitHub Pages](https://brunoCalcAnestesica.github.io/medcalc-app/)
          
          ### Installation
          1. Download the APK file
          2. Enable "Install from unknown sources" on your Android device
          3. Install the APK
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
