name: Security Analysis

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run security audit
      run: flutter pub audit
      
    - name: Check for security vulnerabilities
      run: |
        echo "Checking for common security issues..."
        
        # Check for hardcoded secrets
        if grep -r "password\|secret\|key\|token" lib/ --include="*.dart" | grep -v "// TODO\|// FIXME\|// NOTE"; then
          echo "⚠️  Potential hardcoded secrets found"
          exit 1
        fi
        
        # Check for debug prints in production code
        if grep -r "print(" lib/ --include="*.dart"; then
          echo "⚠️  Debug prints found in production code"
          exit 1
        fi
        
        echo "✅ Security scan completed"

  dependency-check:
    name: Dependency Security Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Check for outdated dependencies
      run: flutter pub outdated
      
    - name: Verify dependency integrity
      run: |
        flutter pub deps --json | jq '.packages | to_entries | map(select(.value.dependency == "direct")) | map(.key) | .[]' | xargs -I {} sh -c 'echo "Checking dependency: {}" && flutter pub deps --json | jq ".packages[\"{}\"]"'

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run comprehensive analysis
      run: |
        echo "Running Flutter analysis..."
        flutter analyze --fatal-infos
        
        echo "Checking code formatting..."
        flutter format --output=none --set-exit-if-changed .
        
        echo "Running tests with coverage..."
        flutter test --coverage
        
        echo "Generating coverage report..."
        flutter test --coverage --coverage-path=coverage/lcov.info
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
